### ISSUE TITLE
Is it very slow for the Wavenet vocoder to synthesize a voice

### ISSUE THREAD

**Issue by hhhuazi** [YoungSeng/Interspeech2022#11]
Hello, I use demo.ippynb synthesizes voice from mel, it takes 5 minutes to synthesize a voice. Isn't this too slow? Can I use HifiGAN's pre training model directly？Thank you for your answer！

**Comment by YoungSeng** [comment]
Yes, it is indeed slow, if you have tried AutoVC and SpeechSplit as well. You can use HifiGAN, but you need to use the corresponding Mel spectrum extractor.
