### ISSUE TITLE
找不到wavenet_vocoder

### ISSUE THREAD

**Issue by IndowK** [YoungSeng/Interspeech2022#12]
作者您好，在运行demo.py的时候，错误提示synthesis.py的12行，找不到wavenet_vocoder。我下载了https://github.com/r9y9/wavenet_vocoder 中的代码，但是没有在里面找到builder。我先请问一下builder是什么，我可以在哪里找到它，或者我其实其他地方出错了？

**Comment by YoungSeng** [comment]
请查看Quick Start 的第二行
Download Speechsplit pre-trained model (pitch decoder 640000-P.ckpt and vocoder checkpoint_step001000000_ema.pth) from [here](https://github.com/auspicious3000/SpeechSplit).

wavenet_vocoder是声码器，可以试试`pip install wavenet_vocoder`，见：SRD-VC/autovc/readme：https://github.com/auspicious3000/autovc
