### ISSUE TITLE
关于路径的问题

### ISSUE THREAD

**Issue by rollingrain** [YoungSeng/Interspeech2022#14]
作者您好，我在运行代码的时候有一些疑问
make_spect_f0.py是提取mel谱和f0，那么source和target文件夹下是分了性别之后的所有vctk数据集中的wav文件（source/p225_001_mic1.wav），还是需要包括子文件夹的wav文件（source/p225/p225_001_mic1.wav）
data_split.py中root = '/ceph/datasets/VCTK-Corpus/wav48/'，我想知道这个路径下的文件类型是什么，是wav16/p225/p225_001_mic1.npy这种形式，还是/VCTK-Corpus-0.92/wav48_silence_trimmed/p225/p225_001_mic1.flac这种形式

**Comment by YoungSeng** [comment]
`make_spect_f0.py` 展示的就是如何做自己的数据集，我这里使用的source是一个男声，target里面是一个女声，作为测试。如下：
![image](https://user-images.githubusercontent.com/37477030/231934464-bc320990-56a8-41b0-9095-276d3ad0a2f9.png)

` '/ceph/datasets/VCTK-Corpus/wav48/'`是原始的VCTK的48kHZ的数据集，我觉得是和16kHZ的数据集一样的格式，但我这里是wav不是npy或者flac
![image](https://user-images.githubusercontent.com/37477030/231934797-41c8dff5-fd2e-49d5-80d7-eeccb8d9e3b6.png)

![image](https://user-images.githubusercontent.com/37477030/231934868-d014bf8d-b237-4d00-9798-28a7c5888581.png)
