### ISSUE TITLE
draw_speaker_embedding提示TypeError

### ISSUE THREAD

**Issue by ShawnPi233** [YoungSeng/Interspeech2022#19]
作者您好，首先很感谢您在VC领域做出的优秀工作，并无私开源。
我最近在尝试运行 draw_speaker_embedding.py 
`speaker_embedding = G2(None, None, None, torch.from_numpy(mel_feature).unsqueeze(0), None) # to (1, len, 80)`
时报错 line 403, in forward content_dim_predict = self.adversarial1(torch.cat((code_exp_1, code_exp_2, code_exp_3), dim=-1))
TypeError: expected Tensor as element 0 in argument 0, but got NoneType 

我的原始mel谱是在16khz采样率音频上得到的shape为(80, length), 仅在加载之后对其进行简单的维度变换`mel_feature = np.transpose(mel_feature, (1, 0))`以适应原代码的输入数据的shape结构。请问是哪里出了问题呢？

希望您能在看到问题时拨冗回复，谢谢！

**Comment by YoungSeng** [comment]
感谢对此工作感兴趣，似乎你的Tensor是一个None，但是我认为这些部分不重要，如果你想可视化特征的话，只需要利用这两行代码可视化你需要可视化的东西就可以了：
https://github.com/YoungSeng/SRD-VC/blob/ee71b992a1889d9937f88f0926672c570bbfbc09/My_model/draw_speaker_embedding.py#L107-L108

**Comment by ShawnPi233** [comment]
> 感谢对此工作感兴趣，似乎你的Tensor是一个None，但是我认为这些部分不重要，如果你想可视化特征的话，只需要利用这两行代码可视化你需要可视化的东西就可以了：
> 
> https://github.com/YoungSeng/SRD-VC/blob/ee71b992a1889d9937f88f0926672c570bbfbc09/My_model/draw_speaker_embedding.py#L107-L108

感谢您的回复。我现在就是想用G2来提取mel谱中的音色的embedding，而不是想要可视化。而原来代码中G2的前三个参数就是None,  因此我参照原先的代码就会报错，请问是需要参考train代码中G2的参数，将三个参数None修改成content, pitch, rhythm？另外，请问该项目代码是否可以实现对一段音频进行语音匿名化，或者说进行音频和音色分离，得到音色特征和去除音色信息的音频？

**Comment by YoungSeng** [comment]
明白了，你应该只使用`encoder_speaker`网络来获取音色，将第400行代码取消注释即可。

https://github.com/YoungSeng/SRD-VC/blob/ee71b992a1889d9937f88f0926672c570bbfbc09/My_model/model.py#L394-L400

**Comment by ShawnPi233** [comment]
> 明白了，你应该只使用`encoder_speaker`网络来获取音色，将第400行代码取消注释即可。
> 
> https://github.com/YoungSeng/SRD-VC/blob/ee71b992a1889d9937f88f0926672c570bbfbc09/My_model/model.py#L394-L400

十分感谢您的耐心解答，我的代码已经可以正常运行了。还有想请问一下我是否可以提取44khz采样率下的歌声音频的128维mel谱，作为训练数据来训练模型？如果可以的话，除了一些数据路径，还需要对原来的代码做特殊的改动吗? 再次感谢！

**Comment by YoungSeng** [comment]
模型应该对音频采样率不敏感，你可以试一试: )

**Comment by ShawnPi233** [comment]
好的，十分感谢
