### ISSUE TITLE
您好！关于F0提取函数speaker_normalization

### ISSUE THREAD

**Issue by ywh-my** [YoungSeng/Interspeech2022#2]
我发现utils.py/speaker_normalization函数里并未对 F0向量中值为 -1e10的值作处理，这样导致 F0中有大量 -1e10的值。代码是否应该作如下修改？
def speaker_normalization(f0, index_nonzero, mean_f0, std_f0):
    # f0 is logf0
    f0 = f0.astype(float).copy()
    #index_nonzero = f0 != 0
    f0[index_nonzero] = (f0[index_nonzero] - mean_f0) / std_f0 / 4.0
    f0[index_nonzero] = np.clip(f0[index_nonzero], -1, 1)
    f0[index_nonzero] = (f0[index_nonzero] + 1) / 2.0
    f0[f0<-1] = 0.0 # 增添这一行。  使得f0估计错误的地方值为0.
    return f0

**Comment by YoungSeng** [comment]
是的，你很仔细，但这部分的操作与[SpeechSplit](https://github.com/auspicious3000/SpeechSplit)是一致的，应该对训练没有影响

https://github.com/YoungSeng/SRD-VC/blob/fc6f89310b019b7553e10668197dd45464772613/My_model/utils.py#L50-L51

只在可视化的时候尝试了这个操作：https://github.com/YoungSeng/SRD-VC/blob/fc6f89310b019b7553e10668197dd45464772613/My_model/draw_f0_distributions.py#L53
