### ISSUE TITLE
您好，希望问一个训练的问题

### ISSUE THREAD

**Issue by ywh-my** [YoungSeng/Interspeech2022#4]
我在VCTK 108 人数据集上进行了训练，使用的特征改为 hifigan的melspec。（声码器也配套用hifigan的）

在各个lr(如1e-4 5e-5)上训练或者 MI LOSS 系数调整为0.005
收敛时，loss基本都是这样的情况：
G/loss_id:0.0003487397,G/loss_id_psnt:0.0001683096,spk_loss:0.0000000000,content_adv_loss:0.0000000000,mi_cp_loss:-0.0000563630,mi_rc_loss:0.0000053062,mi_rp_loss:-0.0000061113,lld_cp_loss:-63.6010932922,lld_rc_loss:-15.7252044678,lld_rp_loss:-63.5549583435,pitch_loss:0.0037977726,

我发现 G/loss_id已经非常小，但是 我 使用 同一条语音 的c r p,去编解码，得到的预测的频谱和原来仍然相差很大，MSEloss达到18000多。 我不知道训练失败的原因，请问您能给予一些建议吗？

**Comment by YoungSeng** [comment]
收敛时的G/loss_id 和 G/loss_id_psnt看起来非常好，结果应该没有问题，所以我怀疑是你的生成代码可能有问题？MSE不应该有这么大；另外 c r p是什么意思？

另外虽然这可能无明显区别，但我建议可以先用AutoVC的特征提取器和声码器试一试

**Comment by ywh-my** [comment]
抱歉。  c r p 是content rthym pitch是缩写。
那我参考 demo.py中的 代码再试试吧~谢谢您。

**Comment by ywh-my** [comment]
尊敬的作者您好！（抱歉又是我）：
    我已经改正了之前的一些错误，用VCTK数据集（108人参与训练）成功训练了您的SRDVC模型。 这是损失函数图：

![image](https://user-images.githubusercontent.com/68546393/191274160-66457f0b-a418-44fc-8270-beb9e7b729ec.png)
![image](https://user-images.githubusercontent.com/68546393/191274391-cff09e68-5ec9-45e4-a435-cbf620b51401.png)
![image](https://user-images.githubusercontent.com/68546393/191274411-83cc780b-9da9-4a26-80b1-656beb0d267f.png)
![image](https://user-images.githubusercontent.com/68546393/191274435-d20b45fc-275d-4f74-9b07-e9c6a0214491.png)

![image](https://user-images.githubusercontent.com/68546393/191274456-e4408955-3551-4f83-9a14-fad263213b16.png)

![image](https://user-images.githubusercontent.com/68546393/191274489-ce736e40-cfe3-43c3-8cf0-34f225f62089.png)
![image](https://user-images.githubusercontent.com/68546393/191274513-aeef6f58-bb01-40bf-a087-431018dbe3c6.png)
最终的训练step的loss的值大概如下：
epoch:148.0000000000,step:543706.0000000000,G/loss_id:0.2087835222,G/loss_id_psnt:0.2024493366,spk_loss:0.0000817477,content_adv_loss:4.6073021889,mi_cp_loss:0.0003967322,mi_rc_loss:0.0003905655,mi_rp_loss:-0.0001250673,lld_cp_loss:-63.4377250671,lld_rc_loss:-14.5912141800,lld_rp_loss:-63.0163841248,pitch_loss:0.0359198488,

我想知道，为什么rthym与Pitch的 MI loss一直在0附近震荡。 content与pitch 的loss则接近0且大于0。 而rthym与content的MI loss 则在0附近剧烈震荡。 这里面我们应该怎样调参才能使得它们互相解耦呢？
MI loss本身的调参应该也比较重要？
谢谢，希望您能够回答，祝您身体健康，工作顺利！

**Comment by ywh-my** [comment]
目前有一定的 音色转换效果，但是不如我自己训练的ADAIN。

**Comment by YoungSeng** [comment]
最终的G/loss_id 和 G/loss_id_psnt看起来没有问题，最终的mi loss 好像也还好，可以参考一下：

- 我们训练时候的一些Loss，在Readme最后的CSDN里面；
- VQMIVC

今晚在Interspeech Live QA上也有不少人问MI训练的问题，事实上，MI的参数我们也是做了一些实验然后找的表现最好的参数，我猜测你说的效果不明显可能是我们特征提取不太一样，可能需要调一下参数。但是，我们做了消融实验，即使去掉MI，one-shot VC应该也可以有较好的效果。不如训练的ADAIN可能是需要调一下参数。

**Comment by hermanseu** [comment]
@YoungSeng   我用集外的数据，测试了下您给出的模型800000-G.ckpt， VC Timbre转换效果确实很好。但是当尝试复现实验时，模型同样训练到800000步，VC Timbre转换效果蛮差的，出来的音频基本上是噪声。找不到原因是什么，是不是有些需要特别注意的地方，您看能给些建议吗？
1. 重现实验时，没有改动代码里面的参数，也没有改动make_spect_f0.py中的参数，甚至训练集合都和代码中的VCTK/wav16/split_speaker.txt保持一致。训练过程中的G/loss_id 和 G/loss_id_psnt和楼上ywh-my给出的差不多，Validation Loss一直都比较大，远大于CSDN中给出的Validation Loss。代码中求loss的时候没有去掉pad部分，同时train时mse_loss用的是mean，validation时用的sum，不知道您是基于什么考虑的？
2. 第二个实验，裁剪了每个音频中首尾过多的silence，去掉了没有说话内容的音频，最终测试时VC出来的音频依然是噪声。

**Comment by YoungSeng** [comment]
您好，从您所说建议：你是在VCTK数据集上训练的吗？Mel extractor和Vocoder是用的和AutoVC一样的吗？如果是一样的话那就和我们实验的环境是一样的了，我没有遇到你说的这个情况，但是我建议调低MI loss的weight（大约是原来的1/10）试试，因为MI似乎不容易训练

1. 关于Loss计算部分，理论上G/loss_id 和 G/loss_id_psnt很小了效果就会很好的，MSE这么低了结果不应该是噪声，请确认Mel extractor和Vocoder以及生成代码没有问题。关于Sum和Mean的计算方式应该对结果不会有影响，这里与Speechsplit是一致的，参见 

（1）https://github.com/auspicious3000/SpeechSplit/blob/10fd57e8fe2570010bbf6dd18ec210c41efe7ddd/solver.py#L166
（2）https://github.com/auspicious3000/SpeechSplit/blob/10fd57e8fe2570010bbf6dd18ec210c41efe7ddd/solver.py#L222

2. 可以先不做这些操作看看效果

**Comment by hermanseu** [comment]
@YoungSeng 谢谢您的迅速回复！

我是在VCTK数据集合训练的，特征是用make_spect_f0.py抽取的，没改动里面的参数设置，如果现在的make_spect_f0.py逻辑是和AutoVC一致的话，应该就是一致的了。不过应该是一致的，因为我用您给出的模型checkpoint_step001000000_ema.pth是可以正常合成音频的。回头我再确认下吧。

关于您说的MI Loss的问题，现在的权重是0.01了， 您的意思是调整成0.001？

**Comment by YoungSeng** [comment]
@hermanseu 我们的Mel谱提取器和Vocoder是和AutoVC和Speechsplit一致的，你现在的情况我建议先follow AutoVC和Speechsplit试试...而且能够复现这两个模型说明你音频特征提取与生成音频的pipeline没有问题

可以这样做，我的意思是：

1. MSE这么小，应该能生成Mel谱，而不是生成噪声的，请检查Mel谱提取器和Vocoder
2. 即使不用MI Loss，利用C1和C2也能完成Timbre Conversion，而不是生成噪声，所以你可以先不用MI loss，即设置权重很小或者直接为0（0就是消融实验了）

**Comment by hermanseu** [comment]
找到问题了，貌似github上默认的make_metadata.py和data_loader.py配合的不是很好，也可能是我数据没有组织好，导致最终加载到训练里面的数据只有每个spk的pxxx_001.npy，所以整个训练里面只用了100条数据，过拟合了。修正后可以正常出音频了。

**Comment by YoungSeng** [comment]
哦居然有这个问题吗，可能是版本控制问题，或者debug的时候被注释掉了...解决好了就好

**Comment by daleth-nobug** [comment]
> 找到问题了，貌似github上默认的make_metadata.py和data_loader.py配合的不是很好，也可能是我数据没有组织好，导致最终加载到训练里面的数据只有每个spk的pxxx_001.npy，所以整个训练里面只用了100条数据，过拟合了。修正后可以正常出音频了。
您好，我最近也遇到了这个问题，想请问一下您是如何解决的呢？我在data_loader.py里class Utterances发现了两处可能与这个问题相关的地方：一是def load_data，此处我已经进行了修改；二是def __getitem__，这里应该如何解决呢？
期盼回复，感谢。
@YoungSeng @hermanseu
