### ISSUE TITLE
strange wav files in the assets/test_result folder

### ISSUE THREAD

**Issue by sajadalipour7** [YoungSeng/Interspeech2022#7]
Hi
I ran demo.py with your checkpoints and the output is good and correct like the outputs in your demo webpage,
but I think the output wav files you provided in the assets/test_result folder in your repository are strange and wrong.

Thank you

**Comment by YoungSeng** [comment]
Yes, you can just ignore this. And I'm glad you pointed this out, I've deleted the assets/test_result folder.
