### ISSUE TITLE
请问这个工作您有没有在libritts上训练过? 如果要在这个数据集上做的话,训练参数的设置上您有什么建议吗

### ISSUE THREAD

**Issue by kerwinchao** [YoungSeng/Interspeech2022#9]

**Comment by YoungSeng** [comment]
我没有尝试过在libritts，但我认为应该结果差不多，如果做音色的VC，我建议可以先不使用MI，只依靠C1和C2就能够完成timbre的迁移了。希望对你有帮助。

**Comment by kerwinchao** [comment]
谢谢你的回答.我还有个问题啊,就是代码里面对于f0的处理已经有了speaker normalization, 是否使用按照性别设置f0的提取范围这个影响大吗?

**Comment by YoungSeng** [comment]
确实值得尝试一下，本项目的归一化音高曲线提取过程和SpeechSplit是一样的；因为VCTK是有性别这个标签的，所以这样做可能提取到的音高曲线会准一些；但是我觉得是否有性别应该对结果影响不大，只是男声和女声音高会更明显高低一些。

**Comment by kerwinchao** [comment]
感谢感谢,我这边没有问题了
